# Generated by Django 5.2.1 on 2025-05-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_artist_first_name_alter_artist_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nom de la troupe')),
                ('logo_url', models.CharField(max_length=255, verbose_name='URL du logo')),
            ],
            options={
                'verbose_name': 'Troupe',
                'verbose_name_plural': 'Troupes',
                'db_table': 'troupes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='troupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='catalogue.troupe', verbose_name='Troupe'),
            preserve_default=False,
        ),
    ]
