# Generated by Django 5.2.1 on 2025-05-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_troupe_artist_troupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='troupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='catalogue.troupe', verbose_name='Troupe'),
        ),
    ]
